framework:
    default_locale: ca
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/templates/dashboard/beers/translations'
        fallbacks:
            - es
        providers:
